### ISSUE TITLE
performance of multiple iSCSI LUNs in one session

### ISSUE THREAD

**Issue by zhuozh** [open-iscsi/tcmu-runner#400]
@mikechristie @dillaman @lxbsz 
LIO will start tx/rx thread per session, session means a link between an initiator with a target.

Suppose I have an SCSI I-T nexus, If the initiator have 20 RBD image to be exported as iSCSI LUNs under a single target, they will share the same tx/rx thread, will it bottleneck the LUN performance? 

Or if I create 20 target, with only one LUN under a target，which means  LIO will create a pair of tx/rx threads for each LUN, will it be a better choice?

By the way, for now, gwcli only support one target, is there any technical consideration?
/> /iscsi-target create target_iqn=iqn.2003-01.com.redhat.iscsi-gw1
Only ONE iscsi target image is supported

**Comment by mikechristie** [comment]
It might be a bottleneck, but we have not seen that be an issue on the target side. When you run your test get some perf/profiling data on the target side so we can check things like if locks are a hotspot.

On the initiator side there are issues in Linux at least. I think because there are some session wide locks they become bottlenecks when doing multiple lun testing. However for ceph iscsi, we have not been able to really stress the iscsi session level limits yet, because we have hit perf issues on the runner/rbd side first :)

There are no technical limits. Gluster actually does a target per LUN.

For ceph iscsi we just thought it would be easier for the user to manage and did not see any perf issues.

I am open to patches to support multiple targets in the ceph-iscsi-* code.

A target/session per LUN is actually better for the ceph iscsi timeout handling because only one image/lun might have an issue but we bring down all sessions due to disabling the tpg.

**Comment by zhuozh** [comment]
Thanks for your detailed explanation, Mike. Very helpful. I will do some perf analysis on target side.

**Comment by hydro-b** [comment]
Multiple iSCSI Targets would allow for strict seperation of iSCSI Targets in different network segments (VLAN, interfaces). Each Target would have it's own Target Portal Groups and Portals. A "per tenant" Target configuration would be possible, exposing only those targets in a specific network to iSCSI clients: similar to what is being done for Ceph based NFS Ganesha.

Use cases: 
- Support migration from traditional enterprise SAN boxes where network segmentation is used.
- PCI DSS compliance. Being able to segmentate the network would make passing PCI DSS audits easier. Otherwise you pretty much have to encrypt all the traffic (IPSEC).

**Comment by mikechristie** [comment]
Closing. Multiple targets is supported in ceph-iscsi 3.x.
