### ISSUE TITLE
data consistency

### ISSUE THREAD

**Issue by qiwuqiang** [open-iscsi/tcmu-runner#420]
hi：
    i have a question about the tcmu, consider following scenario：

1，Iscsi initiator establishes two session connection with gw1,gw2 at
the same time. gw1  is the active path.

2,  The active path is switched to gw 2 due to the interruption of the
connection from the initiator to gw1.

3, gw2  acquire exclusive lock and write some data to lun0.  then gw1
update the exclusive lock to UNLOCKED.

4, after step 3,   some old  iscsi session  inflight write ios
arrival gw1 , gw1  acquire the exclusive lock again, the old data will
  overwrite new data.

**Comment by mikechristie** [comment]
With implicit alua that could only happen if a command got stuck in certain places in the kernel due to a bug like a process getting hung. With explicit alua that would not happen because the outstanding IOs would be queued before a STPG. The IOs would be failed then we would process the STPG and we would then grab the lock.

**Comment by mikechristie** [comment]
Oh yeah explicit support is in the master branch and 1.4.0-rc1. It is not in 1.3.0.

**Comment by mikechristie** [comment]
Closing this assuming you are the same person that posted this to target-devel. We can discuss there. This has also been discussed on ceph-devel and here https://github.com/open-iscsi/tcmu-runner/pull/384 too.

**Comment by qiwuqiang** [comment]
@mikechristie , thanks!
