### ISSUE TITLE
iscsi_trx occupies cpu 100%

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#490]
hi, I write data through tcmu, when the underlying storage space is exhausted, iscsi_trx will occupy 100% of the cpu, you need to restart the tcmu-runner service to recover. The reason for this problem is that command processing is blocked?thanks

![image](https://user-images.githubusercontent.com/29769310/47892599-9bc8ff80-de93-11e8-950b-bae23ae21938.png)

![image](https://user-images.githubusercontent.com/29769310/47892530-2d843d00-de93-11e8-9d48-c87b55ac38b7.png)

![image](https://user-images.githubusercontent.com/29769310/47892632-c1ee9f80-de93-11e8-810d-b1693f86f15d.png)

the system kernel is 3.10.0-862.14.4.el7.x86_64

**Comment by NUABO** [comment]
In fact, I artificially dd a file, occupying a part of the space of the underlying storage file system, and then mount the copy data through iscsiadmin. When the threshold is reached, the asynchronous write of the tcmu handler plugin is error, and no space is found. When iscsi_trx occupies 100% cpu

**Comment by mikechristie** [comment]
What kernel version is this with? I think this was a bug we fixed with this patch:

commit af1dd7ff46824a94da1d90443bd07db2796bd545
Author: Mike Christie <mchristi@redhat.com>
Date:   Tue Nov 28 12:40:39 2017 -0600

    tcmu: don't block submitting context for block waits


We basically used to block the iscsi trx thread when ring space ran out. If a iscsi ping is sent and it times out we would then end up in a endless loop.

**Comment by NUABO** [comment]
hi @mikechristie , the kernel version I am using is 3.10.0-862.14.4.el7.x86_64.Is it because my kernel version is too low?
![image](https://user-images.githubusercontent.com/29769310/47975038-2fded500-e0e7-11e8-8ddb-b0c638f05b02.png)

**Comment by mikechristie** [comment]
Yes that kernel has the bug. One way to workaround the bug is to set qfull_timeout=0. This will have tcmu not going into the wait for space and instead return QUEUE FULL immediately. On the initiator side this will cause extra retries and more traffic on the network though.

Are you using centos or do you have access to RHEL? The RHEL 7.6 kernel has the needed fix and is out now. When centos 7.6 is out it will also have the fix, but I do not know dates for their releases.

**Comment by NUABO** [comment]
@mikechristie  Thanks a lot, I am using the centos system, I tried to replace the 4.19-1 kernel, and now this problem no longer appears. 
In addition to solving this bug in the rhel(centos) 7.6 kernel, will other new tcmu features be added to the  7.6 OS kernel? If so, there is no need to replace the kernel.

**Comment by NUABO** [comment]
thanks
