### ISSUE TITLE
Failed to activate service 'org.kernel.TCMUService1

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#510]
hi，when I restarted the tcmu-runner service, it failed. I checked the log as follows：
(The kernel I am using is 3.10.0-957.1.3.el7.x86_64)
>Dec  8 10:37:23 node3 tcmu-runner: dyn_config_start:422: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
Dec  8 10:37:23 node3 kernel: tcmu daemon: command reply support 1.
Dec  8 10:38:03 node3 dbus[3212]: [system] Activating via systemd: service name='org.kernel.TCMUService1' unit='tcmu-runner.service'
Dec  8 10:38:03 node3 dbus-daemon: dbus[3212]: [system] Activating via systemd: service name='org.kernel.TCMUService1' unit='tcmu-runner.service'
Dec  8 10:38:28 node3 dbus[3212]: [system] Failed to activate service 'org.kernel.TCMUService1': timed out
Dec  8 10:38:28 node3 dbus-daemon: dbus[3212]: [system] Failed to activate service 'org.kernel.TCMUService1': timed out
Dec  8 10:38:53 node3 systemd: tcmu-runner.service start operation timed out. Terminating.
Dec  8 10:38:53 node3 systemd: Failed to start LIO Userspace-passthrough daemon.
Dec  8 10:38:53 node3 systemd: Unit tcmu-runner.service entered failed state.

Is my kernel version too low? thanks

**Comment by mikechristie** [comment]
I have seen the tcmu-runner "timed out" error, but this was because something like the ceph/gluser cluster was not reachable and so we timed out waiting trying to reach it. Do you see any extra errors in /var/log/tcmu-runner.log?

It looks like you are hitting a issue with trying to reconnect to dbus. I have not seen that error before. Is there anything else in /var/log/messages?

I do not think it has anything to do with the kernel for once :)

What command did you run to restart the service? Was it just the normal

systemctl restart tcmu-runner

?

Were you running any other commands at the time? Like doing a targetcli, gwcli, gluster-block command?

Were iscsi initiators connected to the target and doing IO at the time?

**Comment by NUABO** [comment]
@mikechristie thanks, The problem is that the plugin is connected to the storage cluster. At that time, I executed systemctl restart tcmu-runner. The system log prompts the timeout. During the error, I also used the targetcli command, this is not successful.

**Comment by mikechristie** [comment]
What plugin were you using? Was it the rbd one? If so what is your ceph version?

In older ceph versions there is a bug where if the rbd tcmu-runner handler/plugin cannot connect to the ceph cluster during the close/shutdown/stop step then we will hang.

If you run targetcli during this time then you will not be able to reach runner since it is stuck waiting.

**Comment by NUABO** [comment]
@mikechristie yes, I am using the rbd device, this problem should be the reason why my ceph 0.94 version is too low.

**Comment by mikechristie** [comment]
For ceph, why don't you use gwcli?

For targetcli, I do not think you can mix and match under the same tpg like that. I think it is kernel limitation. I think the chap line is in red because the chap username and password is not set, so I think it means there is no authentication setup or it is partially setup.

**Comment by NUABO** [comment]
I will change the tool.
thanks for your help，I will reconfirm my operation.
