### ISSUE TITLE
handle_unmap_internal, Illegal parameter list LBA count

### ISSUE THREAD

**Issue by serjponomarev** [open-iscsi/tcmu-runner#584]
After update to tcmu-runner 1.5.1 (shaman repo) I get an error in the logs:
`tcmu-runner[1641]: handle_unmap_internal:420 rbd/rbd.storage-02: Illegal parameter list LBA count 57344 exceeds:32768`
what could be the problem?

Centos 7.6
Kernel 5.2.6
Ceph Nautilus 14.2.2

**Comment by mikechristie** [comment]
It means tcmu-runner thinks the initiator sent a command that was longer than is supported. The problem is that runner is reporting it supports a longer than supported command. It is a regression that got added in this commit:

commit 117e84c24e51ceaee71ee8f999d4ee05564df02a
Author: Yaowei Bai <baiyaowei@cmss.chinamobile.com>
Date:   Tue Sep 18 18:29:44 2018 +0800

    libtcmu: move SCSI helpers out of libtcmu

because that patch must have used a older version of the code when it got moved.

I will upload a fix and new rpm today.

**Comment by serjponomarev** [comment]
Thanks!

**Comment by serjponomarev** [comment]
@mikechristie all working, thx.

**Comment by mikechristie** [comment]
@serjponomarev Thanks for testing so quickly.

New tcmu-runner rpm build:

https://shaman.ceph.com/repos/tcmu-runner/master/9c84f7a4348ac326ac269fbdda507953dba6ec2c/default/135114/
